# Generated by Django 4.0.5 on 2022-07-25 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('ApellidoPaterno', models.CharField(max_length=45)),
                ('ApellidoMaterno', models.CharField(max_length=45)),
                ('Email', models.EmailField(max_length=254)),
                ('FechaNacimiento', models.DateField()),
                ('Usuario', models.CharField(max_length=35)),
                ('Clave', models.CharField(max_length=45)),
                ('ImgPerfil', models.ImageField(null=True, upload_to='PerfilUsuarios')),
            ],
        ),
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Esqueleto.usuario')),
                ('CallePrincipal', models.CharField(max_length=120)),
                ('CalleSecundaria', models.CharField(max_length=120, null=True)),
                ('Provincia', models.CharField(max_length=45)),
                ('Ciudad', models.CharField(max_length=50)),
                ('Pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='telefono',
            fields=[
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Esqueleto.usuario')),
                ('Telefono1', models.CharField(max_length=10)),
                ('Telefono2', models.CharField(max_length=10, null=True)),
                ('Celular', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='vender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='Esqueleto.usuario')),
                ('Vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vendedor', to='Esqueleto.usuario')),
            ],
        ),
    ]
