# Generated by Django 4.0.5 on 2022-07-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esqueleto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ImgPerfil',
            field=models.ImageField(default='PerfilUsuarios/PerfilDefaulth.jpg', null=True, upload_to='PerfilUsuarios'),
        ),
    ]
