# Generated by Django 4.0.5 on 2022-07-29 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Esqueleto', '0002_alter_usuario_imgperfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=120)),
                ('Descripcion', models.CharField(max_length=200)),
                ('EstadoProducto', models.IntegerField(choices=[(1, 'Nuevo'), (2, 'Usado')], default=1)),
                ('Categoria', models.IntegerField(choices=[(1, 'Clasico'), (2, 'Retro'), (3, 'Ropa'), (5, 'Deportivo'), (6, 'Electronicos'), (7, 'Tecnologia'), (8, 'Arte'), (9, 'Salud'), (10, 'Entretenimiento'), (11, 'Software'), (12, 'Automotriz'), (12, 'Otro')], default=1)),
                ('PaisOrigen', models.IntegerField(choices=[(1, 'Ecuador'), (2, 'EEUU'), (3, 'Peru'), (4, 'Colombia'), (5, 'Venezuela'), (6, 'Brasil'), (7, 'Uruguay'), (8, 'Chile'), (9, 'Bolivia'), (10, 'Paraguay'), (11, 'Otro')], default=1)),
                ('Color', models.IntegerField(choices=[(1, 'Amarillo'), (2, 'Azul'), (3, 'Rojo'), (4, 'Naranja'), (5, 'Verde'), (6, 'Morado'), (7, 'Rosado'), (8, 'Negro'), (9, 'Gris'), (10, 'Cafe'), (11, 'Blanco'), (12, 'Otro')], null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='direccion',
            name='Provincia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='Usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='PersonaDireccion', serialize=False, to='Esqueleto.usuario'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='Usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Propietario', serialize=False, to='Esqueleto.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Email',
            field=models.EmailField(max_length=350),
        ),
        migrations.CreateModel(
            name='publicacionarticulo',
            fields=[
                ('Articulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Esqueleto.articulo')),
                ('Titulo', models.CharField(max_length=120)),
                ('Descripcion', models.CharField(max_length=120)),
                ('Stock', models.IntegerField()),
                ('EstadoPublicacion', models.BooleanField()),
                ('FechaHoraSubida', models.DateTimeField()),
                ('FechaHoraRetirada', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='subasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('FechaHora', models.DateTimeField()),
                ('Estado', models.BooleanField()),
                ('Usuario', models.ManyToManyField(related_name='Participante', to='Esqueleto.usuario')),
                ('PublicacionArticulo', models.ManyToManyField(to='Esqueleto.publicacionarticulo')),
            ],
        ),
        migrations.CreateModel(
            name='favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activo', models.BooleanField()),
                ('FechaHora', models.DateTimeField()),
                ('PublicacionArticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Esqueleto.publicacionarticulo')),
            ],
        ),
        migrations.CreateModel(
            name='CrearPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Autor', to='Esqueleto.usuario')),
                ('PublicarArticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Esqueleto.publicacionarticulo')),
            ],
        ),
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comentario', models.CharField(max_length=350)),
                ('FechaHora', models.DateTimeField()),
                ('PublicacionArticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Esqueleto.publicacionarticulo')),
            ],
        ),
    ]
