# Generated by Django 4.0.5 on 2022-07-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esqueleto', '0003_articulo_alter_direccion_provincia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='ImgArticulo',
            field=models.ImageField(default='Articulos/Nada.jpg', null=True, upload_to='Articulos'),
        ),
    ]
