# Generated by Django 4.0.5 on 2022-08-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esqueleto', '0004_articulo_imgarticulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionarticulo',
            name='DineroInicial',
            field=models.FloatField(default=0.0),
        ),
    ]
