# Generated by Django 4.0.5 on 2022-08-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esqueleto', '0006_alter_crearpublicacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionarticulo',
            name='Usuario',
            field=models.ManyToManyField(to='Esqueleto.usuario'),
        ),
        migrations.DeleteModel(
            name='CrearPublicacion',
        ),
    ]
