# Generated by Django 4.0.5 on 2022-08-06 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Esqueleto', '0007_publicacionarticulo_usuario_delete_crearpublicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='publicacionarticulo',
            name='Usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Publicaciones',
            field=models.ManyToManyField(through='Esqueleto.UsuarioPublicacion', to='Esqueleto.publicacionarticulo'),
        ),
        migrations.AddField(
            model_name='usuariopublicacion',
            name='PublicacionArticulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Esqueleto.publicacionarticulo'),
        ),
        migrations.AddField(
            model_name='usuariopublicacion',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Esqueleto.usuario'),
        ),
    ]
