# Generated by Django 4.0.5 on 2022-08-06 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Esqueleto', '0008_usuariopublicacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubastarPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('FechaHora', models.DateTimeField()),
                ('Estado', models.BooleanField()),
                ('PublicacionArticulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Publicaciones', to='Esqueleto.publicacionarticulo')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='Subasta',
            field=models.ManyToManyField(related_name='EntrarSubasta', through='Esqueleto.SubastarPublicacion', to='Esqueleto.publicacionarticulo'),
        ),
        migrations.DeleteModel(
            name='subasta',
        ),
        migrations.AddField(
            model_name='subastarpublicacion',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Esqueleto.usuario'),
        ),
    ]
