# Generated by Django 4.0.5 on 2022-08-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esqueleto', '0011_alter_articulo_imgarticulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='Categoria',
            field=models.IntegerField(choices=[(1, 'Clasico'), (2, 'Retro'), (3, 'Ropa'), (4, 'Deportivo'), (5, 'Electronicos'), (6, 'Tecnologia'), (7, 'Arte'), (8, 'Salud'), (9, 'Entretenimiento'), (10, 'Software'), (11, 'Automotriz'), (12, 'Otro')], default=1),
        ),
    ]
